version: '3'
services:
  ros-dev:
    image: ros-project
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./src:/catkin_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true
