controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - l_gripper_finger_joint
      - r_gripper_finger_joint
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: POSE_ZERO
  - group: hand
    pose: POSE_HAND_CLOSED